import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "@/contexts/ChatContext";
import Head from "next/head";
import { ReactNode } from "react";
import Background from "@/components/Background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <body className={inter.className}>
        <Background />
        <div className='relative z-10'>
          <ChatProvider>{children}</ChatProvider>
        </div>
      </body>
    </html>
  );
}
